#hapus -example dan isi konfigurasi dibawah ini dengan menggunakan base 64 dari nilai asli

apiVersion: v1
kind: Secret
metadata:
  name: linkz-secret
type: Opaque
data:
  # Contoh: base64 dari "mysql://root:nasiuduk1@mysql-service:3306/linkz_db"
  DATABASE_URL: "bXlzcWw6Ly9yb290Om5hc2l1ZHVrMUBteXNxbC1zZXJ2aWNlOjMzMDYvbGlua3pfZGI="

  DB_PASSWORD: "bmFzaXVkdWsx"

  BETTER_AUTH_SECRET: "" 
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  RESEND_API_KEY: ""